# Generated by Django 2.2.16 on 2022-01-02 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220102_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(help_text='Автор, на которого подписывается пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='who_subscribed', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
